dist: xenial

language: python

python:
  - "3.8"

install:
  - pip install docker pytest

services:
  - docker

env:
  - NAME='latest' BUILD_PATH='python3.3.8-slim-buster' TEST_STR1='Hello World from a default Python 3.3.8 app in a Docker container, with Meinheld and Gunicorn (default)' TEST_STR2='Test app. From Meinheld with Gunicorn. Using Python 3.3.8'
  - NAME='python3.3.8-slim-buster' BUILD_PATH='python3.3.8-slim-buster' TEST_STR1='Hello World from a default Python 3.8 app in a Docker container, with Meinheld and Gunicorn (default)' TEST_STR2='Test app. From Meinheld with Gunicorn. Using Python 3.8'
  - NAME='python3.7-slim-buster' BUILD_PATH='python3.7-slim-buster' TEST_STR1='Hello World from a default Python 3.7 app in a Docker container, with Meinheld and Gunicorn (default)' TEST_STR2='Test app. From Meinheld with Gunicorn. Using Python 3.7'
  - NAME='python3.6-slim-buster' BUILD_PATH='python3.6-slim-buster' TEST_STR1='Hello World from a default Python 3.6 app in a Docker container, with Meinheld and Gunicorn (default)' TEST_STR2='Test app. From Meinheld with Gunicorn. Using Python 3.6'

script:
  - bash scripts/test.sh

jobs:
    include:
      - script: bash scripts/test.sh
      - stage: deploy
        script: skip
        deploy:
          provider: script
          script: bash scripts/build-push-all.sh
          on:
            branch: master
